version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sompolcdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: secret
      PGDATABASE: sompolcdb
    depends_on:
      - postgres
    ports:
      - "3000:3000"
 
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
